### ISSUE TITLE
404 Island component not found

### ISSUE THREAD

**Issue by boumanb** [harlan-zw/nuxt-og-image#49] opened 2023-05-16 22:31 UTC
I'm experiencing this issue currently.

In `components/islands/MyOgImage.vue`
```vue
<script setup lang="ts">
const props = defineProps({
  title: String,
})
</script>

<template>
  <div class="w-full h-full flex text-white bg-blue-500 items-center justify-center">
    <h1 :style="{ fontSize: '70px' }">
      {{ title }} 👋
    </h1>
  </div>
</template>
``` 

in `app.vue`
```vue
<template>
  <SeoKit />
  <OgImageStatic component="MyOgImage" />
  <NuxtPage />
</template>

<style>
html {
  font-family: $dt('font.sans');
}
</style>

```

Resulting in error
```
Vue warn]: Component <Anonymous> is missing template or render function.          12:26:18 AM
[12:26:18 AM] [nuxt] [request error] [unhandled] [404]  (404 Island component not found: undefined (/__nuxt_island/MyOgImage.........
```

_Originally posted by @boumanb in https://github.com/harlan-zw/nuxt-og-image/issues/40#issuecomment-1550440323_

**Comment by harlan-zw** [comment] 2023-05-20 17:00
Hi @boumanb, thanks for the issue.

Would it be possible prodivde a StackBlitz reproduction? It would help me out a lot :pray:

**Comment by BillyBouman-2B-IT** [comment] 2023-05-21 11:53
> Would it be possible prodivde a StackBlitz reproduction? It would help me out a lot 🙏

https://stackblitz.com/edit/nuxt-starter-rcgvwy?file=app.vue
Images aren't being generated on Stackblitz sadly. I've spend some time trying to get them to work, without success.

The error is triggered by navigating to the OG image previewer, I manually appended `__og_image__` to the url.
<img width="1120" alt="afbeelding" src="https://github.com/harlan-zw/nuxt-og-image/assets/127685984/95bc77ea-c80f-45a2-b41a-c8306db44d3c">

**Comment by harlan-zw** [comment] 2023-06-04 11:54
Hey, so I've investigated this one and the issue seems to be related to your config, specifically these lines:

```ts
components: [
    { path: 'components', global: true },
  ],
```

The problem is that when you set this, you're resetting how the islands folder behaves. I'd recommend that you just create a `component/global` folder that does the same thing.

Not sure if there's anything the module can do to resolve this so I'll close this.

**Closed by harlan-zw** 2023-06-04 11:54 UTC
