### ISSUE TITLE
Module not working with Netlify

### ISSUE THREAD

**Issue by schneider-carlo** [harlan-zw/nuxt-og-image#51] opened 2023-05-22 13:49 UTC
### Describe the bug

When using this module on netlify you will get a white box when you open up the url for the og:image.

### Reproduction

git@github.com:schneider-carlo/nuxt-og-image-issue.git

### System / Nuxt Info

```Shell
- Operating System: `Darwin`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.5.1`
- Nitro Version:    `2.4.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`, `ogImage`
- Runtime Modules:  `nuxt-og-image@2.0.0-beta.40`
- Build Modules:    `-`
```

**Comment by harlan-zw** [comment] 2023-05-24 03:08
Duplicate of https://github.com/harlan-zw/nuxt-og-image/issues/51, closing

**Closed by harlan-zw** 2023-05-24 03:08 UTC
