### ISSUE TITLE
new title weridness

### ISSUE THREAD

**Issue by jpengelbrecht** [harlan-zw/nuxt-og-image#92] opened 2023-10-05 09:35 UTC
### Describe the bug

titles work fine on page,  however og image cant read it.  I am using  "nuxt-seo-kit": "1.3.13" and  "nuxt-og-image": "2.0.25" i also tried "nuxt-og-image": "2.1.1",

### System / Nuxt Info

```Shell
------------------------------
- Operating System: Darwin
- Node Version:     v18.10.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@8.19.2
- Builder:          -
- User Config:      modules, site, turnstile, sitemap, robots, schemaOrg, linkChecker, app, routeRules, extends, typescript, sourcemap, devServer, htmlValidator, image, runtimeConfig, nitro, appConfig, ignore, hooks, css, vite
- Runtime Modules:  @pinia/nuxt@0.4.11, @nuxt/content@2.7.2, @nuxt/image@1.0.0-rc.3, @vueuse/motion/nuxt@2.0.0, nuxt-calendly@0.1.14, vue3-carousel-nuxt@1.1.0, @nuxtjs/turnstile@0.6.3
- Build Modules:    -
------------------------------
```

**Comment by jpengelbrecht** [comment] 2023-10-05 11:19
seems to be related to nuxt version < 3.7.1

**Comment by harlan-zw** [comment] 2023-10-05 11:23
Are you able to provide a reproduction https://stackblitz.com/edit/nuxt-starter-pxs3wk?file=pages/index.vue

:pray:

**Comment by jpengelbrecht** [comment] 2023-10-05 13:31
@harlan-zw  that that blitz with be able to reproduce the issue,  the issue is with seo toolkit and og image,  somehow the title doesnt like through after nuxt 3.7.1 when using a OG image static template.  
![image](https://github.com/harlan-zw/nuxt-og-image/assets/93583336/944546e7-d528-4500-8e2d-77d89da9b1f8)

What is also interesting is updating to your https://www.npmjs.com/search?q=nuxtseo%20module new module solves it.  but the module is still new and hard to migrate to at the moment. 

so the issue seems to be between "nuxt": "3.7.4",  "nuxt-seo-kit": "1.3.12", "nuxt-og-image": "2.0.25", and using templates described here https://nuxtseo.com/og-image/getting-started/your-first-template.  

sorry i wish i could be more help,  though i cant figure out how to do a reproduction for you other than a starter repo

**Comment by harlan-zw** [comment] 2023-12-09 07:51
Seems to be fixed in the latest versions. You will need to upgrade to [Nuxt SEO](https://nuxtseo.com/nuxt-seo/getting-started/installation).

Let me know if you're still having issues though.

**Closed by harlan-zw** 2023-12-09 07:51 UTC
