### ISSUE TITLE
How to add the image?

### ISSUE THREAD

**Issue by jeannen** [harlan-zw/nuxt-og-image#105] opened 2023-10-29 10:10 UTC
### Details

Hi!

I just downloaded the module, and made a template, but I can't figure out how to actually add the picture to my og:image

I added `defineOgImage()` in my app.vue (also tried in index.vue) but the image is not added. It's properly detected by the OG image debug tool, but not by the OpenGraph debug tool

Debug tools:
<img width="1253" alt="image" src="https://github.com/harlan-zw/nuxt-og-image/assets/4388849/632836ed-8b6e-4eaa-89d4-38f8440b5b08">
<img width="1254" alt="image" src="https://github.com/harlan-zw/nuxt-og-image/assets/4388849/fd2c30ac-1f45-475f-ac61-06e391764982">

Am I missing something? 😅

Edit:
After doing npm run build, I get this in my HTML:
```HTML
<meta name="twitter:image:src" content="http://localhost:3000/__og_image__/og.png">
```

When I go to the link, I get `Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/nicol/Documents/Dev/apps/jeannen-com/.output/server/chunks/error-500.mjs' imported from /Users/nicol/Documents/Dev/apps/jeannen-com/.output/server/chunks/nitro/node-server.mjs`

**Comment by harlan-zw** [comment] 2023-10-29 10:34
Hey @jeannen, thanks for the issue :)

Afaik the devtools image preview is broken. All you should need is `defineOgImage` and all tags should be added for you that are needed.

I think there is a regression in the latest version that isn't picking up the request origin, you can get around it by manually providing your site url.

```ts
export default defineNuxtConfig({
  site: 'https://example.com
})
```

See https://nuxtseo.com/og-image/getting-started/prerender-requirements. Currently investigating this.

As for this error, I'm not too sure, can you provide any more details to help me reproduce?

**Comment by jeannen** [comment] 2023-10-29 11:29
That's odd, I tried to do `npm i` and it seems to have fixed the error 😅


Seems to work so far (haven't tested in prod yet) except for the default values of title / descriptions. From what I understand, if no parameters are provided, it will take the default meta title & description. However, on some of my pages, the title is changed via and it doesn't seems to catch up automatically

If I use `defineOgImage({ title: doc?.title, description: doc?.description })` it works fine tho, but I have to explicitly mention it. Could be nice if it was executed after the <script> so it auto-catch up with the tags!

```vue
<template>
    <main>
        <p class="article-date">{{ formatedDate }}</p>
        <h1 class="article-title">{{ doc?.title }}</h1>
        <NuxtImg class="article-img" :src="coverImagePath" :alt="doc?.title" width="500px" />
        <ContentRenderer :value="doc" class="page-formating" />
    </main>
</template>

<script setup lang="ts">
    useHead({
        script: [
            {
                src: 'https://platform.twitter.com/widgets.js',
                async: true,
                defer: true,
            },
        ],
    })
    useSeoMeta({
        ogType: 'article',
        titleTemplate: '%s | Jeannen Blog',
    })


    const route = useRoute()
    //@ts-ignore
    const fullSlug = '/blog/' + route.params.slug.join('/')
    const { data, error } = await useAsyncData(fullSlug, () => queryContent(fullSlug).findOne())

    const doc = data.value

    if (!doc) throw { statusCode: 404, message: 'Post not found' }
    if (error.value) handleError(error.value)

    const docFullUrl = 'https://jeannen.com' + doc._path
    const formatedDate = new Date(doc.createdAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
    const coverImagePath = `https://jeannen.com/images/blog/${doc.coverImage}`
    const bodyText = doc.body.children.map(element => element.children ? element.children[0]?.value : '').join('\n');
    //
    defineOgImage({ title: doc?.title, description: doc?.description })

    useSchemaOrg([...])

    function handleError(error: Object | any) {
        throw { statusCode: error?.statusCode, message: error?.statusMessage }
    }
</script>

```


Oh also, also, useSeoMeta({ ogImage: 'https://url.com/image.png' }) seems to override the og:image (but not the twitter one?). Could be nice to let `defineOgImage` override both and use `useSeoMeta` as backup

**Comment by harlan-zw** [comment] 2023-10-30 08:42
> the title is changed via and it doesn't seems to catch up automatically

This would hint that the SSR response isn't returning the right values, maybe a async issue?

> Oh also, also, useSeoMeta({ ogImage: '[url.com/image.png](https://url.com/image.png)' }) seems to override the og:image (but not the twitter one?). Could be nice to let defineOgImage override both and use useSeoMeta as a backup.

Using `defineOgImage` will always override all of the tags, if you use useSeoMeta afterward then it won't replace all of the tags.

I've just pushed up a way to handle this. (docs will be updated soon)

```ts
/* app.vue */
// setting a runtime image for all pages
defineOgImage({ component : 'root'  })

/* pages/static.vue */
// overriding the image using a prebuilt one
defineOgImage({ url : 'https://some-domain.png/static.png', width: 1200, height: 630, alt: 'My Image'  }) 
```

> Edit: Also, my image doesn't seem to work. It appear on the preview tool but not the final png/Svg (it's in the /public folder)

Most likely the issue is that you're not providing valid HTML, you need to use just a number of the width, I'd also recommend setting an explicit height for SVGs as it can't infer the dimensions. These are limitations of Satori which powers the runtime images.

```html
<img class="profile-icon" src="/images/profile-pic-color.svg" width="150" height="150">
```

If you need some hands-on help with Nuxt / OG Image, happy to jump on a call if it would be useful for you.

**Comment by jeannen** [comment] 2023-11-01 11:27
Thanks a lot for the reply!

> I've just pushed up a way to handle this in v2.2.2.

So, this means og images will now inherit properties from the parents? 



> Most likely the issue is that you're not providing valid HTML

Oh, yes I size my image using CSS, I need to explicitly add the size in the HTML?

And thanks a lot for the support! 😀 I managed to get my personal blog updated, so far I didn't encountered huge issues, it's mainly organizing everything that gives me trouble haha

**Comment by nathanchase** [comment] 2023-11-01 13:02
@harlan-zw FWIW, I'm finding that if I use these three, in this order:
`useSchemaOrg()`
`useSeoMeta`
`defineOgImage`

it does correctly attribute `og-image` to the one I've defined in `defineOgImage`:
<meta property="og:image" content="http://localhost:3000/mypage/__og_image__/og.png">

but it does something weird with Twitter image, creating two different property names:
<meta name="twitter:image" content="http://localhost:3000/default.png"> // <- this one seems to be from `useSeoMeta`
<meta name="twitter:image:src" content="http://localhost:3000/mypage/__og_image__/og.png"> // <- this one is by `defineOgImage`

**Comment by harlan-zw** [comment] 2023-12-09 08:53
Thanks for flagging that, there's a fix for this in v3.

In v3 you can also use `defineOgImage({ url: '/default.png, width: <width>, height: <height> })` to add an existing image, should be a bit easier than trying to get `useSeoMeta` tags to be in sync with `defineOgImage`.

**Closed by harlan-zw** 2023-12-09 08:53 UTC
